### PR TITLE
Add HTTP/2 Connector

### PR DESCRIPTION
**Pull request by ethan92429**
This is an attempt to build the client with HTTP/2 support.

### CODE REVIEW

**Review by harmanpa — CHANGES_REQUESTED** [review]
com.github.nhenneaux.jersey.connector.httpclient:jersey-httpclient-connector is GPL 3.0 :-(

**Comment by awk** [comment]
We cannot take on board a GPL 3.0 requirement into this SDK I'm afraid.

It will infect not merely the SDK but anything that depends upon it - which is (potentially) all third-party usages (or other uses within PTC). Not something that's acceptable.

**Comment by ethan92429** [comment]
Looks like the author will be changing the license to LGPL so we can use it! Go open source! https://github.com/nhenneaux/jersey-httpclient-connector/issues/8

**Review by harmanpa — APPROVED** [review]
Can I defer this one to @awk on the licensing topic - if it's fine for PTC it's fine for us!

**Pull request merged**
